scraping:
    driver_path: chromedriver.exe
    base_url: https://autoplius.lt/skelbimai/naudoti-automobiliai?make_id=19524&page_nr=
    pages_to_scrape: 3
    page_title_text: Tesla Naudoti automobiliai
    page_title_selector: .js-search-title
    selector_title: .announcement-item .announcement-title
    selector_price: .announcement-item .announcement-pricing-info strong
logging:
    log_file_name: main.log